In [1]:
# Import librarey
import numpy as np
import pandas as pd
import pandas_profiling
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Importing the dataset
df=pd.read_csv(r"C:\Users\Lenovo\Desktop\Data\PIDD Data.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   Diabetes function  Age  Class  
0              0.627   50      1  
1              0.351   31      0  
2              0.672   32      1  
3              0.167   21      0  
4              2.288   33      1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Pregnancies        768 non-null    int64  
 1   Glucose            768 non-null    int64  
 2   BloodPressure      768 non-null    int64  
 3   SkinThickness      768 non-null    int64  
 4   Insulin            768 non-null    int64  
 5   BMI                768 non-null    float64
 6   Diabetes function  768 non-null    float64
 7   Age                768 non-null    int64  
 8   Class              768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [16]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [17]:
scaled=sc.fit_transform(df)
scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.46849198,
         1.4259954 ,  1.36589591],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.36506078,
        -0.19067191, -0.73212021],
       [ 1.23388019,  1.94372388, -0.26394125, ...,  0.60439732,
        -0.10558415,  1.36589591],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.68519336,
        -0.27575966, -0.73212021],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.37110101,
         1.17073215,  1.36589591],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.47378505,
        -0.87137393, -0.73212021]])

In [18]:
# Apply 1st ML method
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca.fit(scaled)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [21]:
df2=pca.transform(scaled)
df2

array([[-1.75694707, -1.11174258],
       [ 1.50742148,  0.55940565],
       [-0.65082201, -1.92957633],
       ...,
       [ 0.57408846, -0.03381634],
       [ 0.17269908, -1.32289215],
       [ 1.32126715,  1.02748861]])

In [27]:
# Setting Up The X value
X=pd.DataFrame(df2)
X.head()

0         1
0 -1.756947 -1.111743
1  1.507421  0.559406
2 -0.650822 -1.929576
3  1.587398  1.065075
4 -2.483374  2.359563

In [26]:
# Setting Up The y Value
y=pd.DataFrame(df['Class'])
y.head()

Class
0      1
1      0
2      1
3      0
4      1

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [38]:
# Apply 2nd ML method
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model_history=lr.fit(X_train,y_train)
model_history

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
pred=lr.predict(X_test)

In [40]:
# Import Accuracy Score and matrix
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
score=accuracy_score(pred,y_test)
score

0.8441558441558441

In [41]:
print(classification_report(pred,y_test))
print(confusion_matrix(pred,y_test))

              precision    recall  f1-score   support

           0       0.86      0.91      0.88        99
           1       0.82      0.73      0.77        55

    accuracy                           0.84       154
   macro avg       0.84      0.82      0.83       154
weighted avg       0.84      0.84      0.84       154

[[90  9]
 [15 40]]
